levels:
    - name: Piece of cake
      castle1: castle01.png
      castle2: castle02.png
    - name: Windy weather
      castle1: castle03.png
      castle2: castle04.png
    - name: Who first?
      castle1: castle05.png
      castle2: castle06.png
